### ISSUE TITLE
adding a link to an image

### ISSUE THREAD

**Issue by rafmix** [simogeo/ckeditor-adv_link#2]
Hello, 
I use CKEditor 4.5.1.

it works well with text, but if I select an image and try to put a link on, link is created but not englobing the image tag, result is like: &nbsp;&lt;a ...&gt;&lt;/a&gt; &lt;img...&gt;, not as needed : &lt;a...&gt;&lt;img ...&gt;&lt;/a&gt;

I unistalled the adv_link to try and it works, so if you have an idea about this issue, thank in advance

raf

**Comment by simogeo** [comment]
Hi Raf,
Thanks for reporting. Indeed, I tried with 4.4.3 and it works well. I guess the plugin should be rewritten for 4.5.1.

If you do it please, let me know. The best way to do that is to use the default [link plugin](https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/link), rename it and add some fixes.

Added pieces of code in current version are target by @simo tag. You can perform search on source to see changes, for example [here](https://github.com/simogeo/ckeditor-adv_link/blob/master/dialogs/link.js).

**If you adapt it, please let me know**.
In case I work on that I'll let you know on that thread.

**Comment by simogeo** [comment]
@rafmix : I rewrited the plugin. It should be ok, now ! Please give me feedback
